#!/bin/sh

#* Copyright (C) 2007 Massimo Del Fedele
#*
#* This program is free software; you can redistribute it and/or modify
#* it under the terms of the GNU General Public License as published by
#* the Free Software Foundation; either version 2 of the License, or
#* (at your option) any later version.
#*
#* This program is distributed in the hope that it will be useful,
#* but WITHOUT ANY WARRANTY; without even the implied warranty of
#* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#* GNU General Public License for more details.
#*
#* You should have received a copy of the GNU General Public License
#* along with this program; if not, write to the Free Software
#* Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#*
#* Authors: Massimo Del Fedele <max@veneto.com>

echo "CMDLINE : $@\n\n" > /tmp/pippo-filter-1.txt
#cat > /tmp/pippo-filter-2.txt
#return 0;
#gs -q -dNOPAUSE -dPARANOIDSAFER -dBATCH -r600x600 -sPAPERSIZE=a4 -sDEVICE=pbmraw -sOutputFile=- -
#   1> /tmp/capt.log 2>&1
gs -q -dNOPAUSE -dPARANOIDSAFER -dBATCH -r600x600 -sDEVICE=pbmraw -sOutputFile="|lbp800 -t 110 -l 110" -
#   1> /tmp/capt.log 2>&1


return 0;
